name: pearl 
description: Dedicated to Lorde's dog. PEARL is Programming Engine For Analysis of Resources & Logs.
# version: 1.0.0
# homepage: https://www.example.com
# author: root <support@bpilotglobal.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async:
    any
  jclosure:
    path: /opt/deployment/dartpackages/jclosure
  dg6library:
    path: /opt/deployment/dartpackages/dg6library
